[package]
name = "euler"
version = "0.1.0"
authors = ["rinp <rinp.mail.mail@gmail.com>"]
include = ["data/*"]

[dependencies]
lazy_static = "0.2"
rayon = "0.6.0"
num = "0.1.37"
time = "0.1"
fnv = "1.0.5"
tempfile = "2.1.5"